# 프로젝트 루트(ipp-reservation-server)에서 실행
cat > fly.toml <<'EOF'
# fly.toml — Fly.io app configuration for ipp-reservation-server
# Docs: https://fly.io/docs/reference/configuration/

app = 'ipp-reservation-server'
primary_region = 'nrt'           # Tokyo region (low latency to Korea)

[env]
  TZ = 'Asia/Seoul'              # Container timezone

[build]                          # Dockerfile auto-detected

[http_service]
  internal_port = 4000           # index.js listens on 4000
  force_https = true

  auto_start_machines  = true
  auto_stop_machines   = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.ports]]
    handlers = ['http']
    port = 80

  [[http_service.ports]]
    handlers = ['tls', 'http']
    port = 443

[[vm]]                           # free tier size
  cpu_kind = 'shared'
  cpus = 1
  memory = '256mb'
EOF

# 내용 확인
cat fly.toml