

# Render Blueprint
# Docs: https://render.com/docs/blueprint-spec

services:
  - type: web
    name: ipp-reservation-server
    env: node            # Use Render's native Node runtime (no Dockerfile)
    plan: free
    region: singapore
    branch: main

    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /

    envVars:
      - key: TZ
        value: Asia/Seoul       # Set container timezone to KST